apiVersion: batch/v1
kind: CronJob
metadata:
  name: step-cd
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: gitops
          containers:
            - name: gitops-operator
              image: spg51/zad2:gitops
              command: [sh, -e, -c]
              args:
                - git clone https://github.com/SenatorP51/config_repo.git /tmp/zad2 && find /tmp/zad2 -name '*.yaml' -exec kubectl apply -f {} \;
